  const replacements = {
    'rdmPLANE': ['PURGATORY', 'GEHENNA', 'HELL', 'THE ABYSS', 'THE DREAMWORLD', 'HEAVEN', 'THE ELEMENTAL PLANE OF FIRE', 'THE ELEMENTAL PLANE OF AIR', 'rdmEARTH', 'THE ELEMENTAL PLANE OF WATER', 'THE ASTRAL SEA'],
    'rdmSIZE': ['', 'GIANT'],
    'rdmNOBLE': ['BARON', 'BARONNESS', 'PRINCE', 'PRINCESS', 'KING', 'QUEEN', 'DUKE', 'DUCHESS', 'MARQUIS', 'MARCHIONESS', 'ARCHBISHOP', 'COUNT', 'COUNTESS', 'BARONNESS', 'EMPEROR', 'EMPRESS', 'PRINCE-ELECTOR'],
    'rdmEARTH': ['THE PLANE OF EARTH', 'THE PLANE OF OOZE', 'THE PLANE OF METAL', 'THE PLANE OF MAGMA', ],
    'rdmFIRE': ['THE PLANE OF FIRE', 'THE PLANE OF LIGHT', 'THE PLANE OF SMOKE', 'THE PLANE OF MAGMA', ],
    'rdmAIR': ['THE PLANE OF AIR', 'THE PLANE OF ELECTRICITY', 'THE PLANE OF SMOKE', 'THE PLANE OF COLD', ],
    'rdmWATER': ['THE PLANE OF WATER', 'THE PLANE OF STEAM', 'THE PLANE OF OOZE', 'THE PLANE OF COLD', ],
  };
